-- liquibase formatted sql
-- changeset Sedep:020

INSERT INTO resumes (applicant_id, name, category_id, salary, is_active, created_date, update_time) VALUES
((SELECT id FROM users WHERE email = 'alex@gmail.com'),
'Java Developer',
(SELECT id FROM categories WHERE name = 'Разработка ПО'),
150000, true, NOW(), NOW()),
((SELECT id FROM users WHERE email = 'alex@gmail.com'),
'Android Developer',
(SELECT id FROM categories WHERE name = 'Разработка ПО'),
140000, true, NOW(), NOW()),
((SELECT id FROM users WHERE email = 'ekaterina@gmail.com'),
'Frontend Developer',
(SELECT id FROM categories WHERE name = 'Разработка ПО'),
130000, true, NOW(), NOW()),
((SELECT id FROM users WHERE email = 'ekaterina@gmail.com'),
'UI/UX Designer',
(SELECT id FROM categories WHERE name = 'Дизайн и UX'),
120000, true, NOW(), NOW()),
((SELECT id FROM users WHERE email = 'dmitry@gmail.com'),
'DevOps Engineer',
(SELECT id FROM categories WHERE name = 'DevOps'),
170000, true, NOW(), NOW()),
((SELECT id FROM users WHERE email = 'dmitry@gmail.com'),
'System Administrator',
(SELECT id FROM categories WHERE name = 'Системное администрирование'),
140000, true, NOW(), NOW()),
((SELECT id FROM users WHERE email = 'anna@gmail.com'),
'QA Engineer',
(SELECT id FROM categories WHERE name = 'Тестирование'),
110000, true, NOW(), NOW()),
((SELECT id FROM users WHERE email = 'anna@gmail.com'),
'Business Analyst',
(SELECT id FROM categories WHERE name = 'Аналитика'),
130000, true, NOW(), NOW()),
((SELECT id FROM users WHERE email = 'sergey@gmail.com'),
'Full Stack Developer',
(SELECT id FROM categories WHERE name = 'Разработка ПО'),
160000, true, NOW(), NOW()),
((SELECT id FROM users WHERE email = 'sergey@gmail.com'),
'Project Manager',
(SELECT id FROM categories WHERE name = 'Управление проектами'),
180000, true, NOW(), NOW()),
((SELECT id FROM users WHERE email = 'olga@gmail.com'),
'Data Scientist',
(SELECT id FROM categories WHERE name = 'Аналитика'),
150000, true, NOW(), NOW()),
((SELECT id FROM users WHERE email = 'olga@gmail.com'),
'Python Developer',
(SELECT id FROM categories WHERE name = 'Разработка ПО'),
140000, true, NOW(), NOW()),
((SELECT id FROM users WHERE email = 'maxim@gmail.com'),
'Information Security Specialist',
(SELECT id FROM categories WHERE name = 'Информационная безопасность'),
160000, true, NOW(), NOW()),
((SELECT id FROM users WHERE email = 'maxim@gmail.com'),
'Network Administrator',
(SELECT id FROM categories WHERE name = 'Системное администрирование'),
130000, true, NOW(), NOW()),
((SELECT id FROM users WHERE email = 'natalia@gmail.com'),
'Content Manager',
(SELECT id FROM categories WHERE name = 'Контент-маркетинг'),
90000, true, NOW(), NOW()),
((SELECT id FROM users WHERE email = 'natalia@gmail.com'),
'SMM Specialist',
(SELECT id FROM categories WHERE name = 'SMM'),
100000, true, NOW(), NOW()),
((SELECT id FROM users WHERE email = 'andrey@gmail.com'),
'PHP Developer',
(SELECT id FROM categories WHERE name = 'Разработка ПО'),
120000, true, NOW(), NOW()),
((SELECT id FROM users WHERE email = 'andrey@gmail.com'),
'Database Administrator',
(SELECT id FROM categories WHERE name = 'Системное администрирование'),
140000, true, NOW(), NOW()),
((SELECT id FROM users WHERE email = 'maria@gmail.com'),
'Frontend React Developer',
(SELECT id FROM categories WHERE name = 'Разработка ПО'),
130000, true, NOW(), NOW()),
((SELECT id FROM users WHERE email = 'maria@gmail.com'),
'Web Designer',
(SELECT id FROM categories WHERE name = 'Дизайн и UX'),
120000, true, NOW(), NOW());